# 地址: https://github.com/Wans-OS/my-backup
# 作者: Wans
# 更新: 2026-04-29 19:38:17
# 描述: 在proxy-providers加入您的机场订阅链接 (代理提供者)

# 订阅锚点，排除了一些节点，例如 包含剩余, 官网, 到期, 也可以在exclude-filter添加你需要排除的节点
FilterPP: &FilterPP "Expire|到期|剩余|Traffic|网址|官网|过期|地址"

# 测速地址
# YouTube
# https://www.youtube.com/generate_204
# Google
# https://www.gstatic.com/generate_204
# https://www.google.com/generate_204
# https://www.google.cn/generate_204
# Cloudflare
# https://cp.cloudflare.com/generate_204
# https://www.qualcomm.cn/generate_204
UrlTest:  &UrlTest 'https://www.gstatic.com/generate_204'

PU: &PU { exclude-filter: *FilterPP, type: http, proxy: DIRECT, interval: 86400, health-check: { enable: true, url: *UrlTest, interval: 300 } }
PF: &PF { exclude-filter: *FilterPP, type: file, proxy: DIRECT, interval: 86400, health-check: { enable: true, url: *UrlTest, interval: 300 } }
# 官方配置文档: https://wiki.metacubex.one/config/proxy-providers/
proxy-providers:
  main:
    <<: *PU
    url: https://anyland.club/#/register?code=R7vdKxbE
    path: ./proxy_provider/main.yaml
    header:
      User-Agent:
        - "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
      token:
        - "*********"
    override:
      udp: true
      additional-prefix: '主-'  # 订阅节点前缀，方便区分该节点属于哪个订阅链接 例如`主-香港🇭🇰

  back:
    <<: *PF
    path: proxy_provider/back.yaml   # 本地文件，内容格式同订阅链接，方便测试和备用
    override:
      udp: true
      additional-prefix: "备-6-"

# 通用配置
mode: rule
ipv6: false
mixed-port: 7890
allow-lan: true
bind-address: '*'
log-level: warning
unified-delay: true
find-process-mode: strict
tcp-concurrent: true
keep-alive-interval: 15
keep-alive-idle: 600


# 规则选择缓存
profile:
  store-selected: true
  store-fake-ip: true
  tracing: true

# DNS配置
dns:
  enable: true
  ipv6: true
  prefer-h3: false
  use-hosts: true
  listen: 0.0.0.0:1053
  use-system-hosts: true
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::/64
  fake-ip-filter:
    - RULE-SET:Lan
    - RULE-SET:China
  fallback:
    - https://dns.adguard-dns.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://dns.cloudflare.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://dns.google/dns-query#ecs=1.1.1.1/24&ecs-override=true
  direct-nameserver-follow-policy: true # 用于 direct 出口域名解析的 DNS 服务器，如果不填则遵循 nameserver-policy、nameserver 和 fallback 的配置
  default-nameserver: # 默认 DNS, 用于解析 DNS 服务器 的域名，必须为 IP, 可为加密 DNS
    - tls://223.5.5.5
    - tls://119.29.29.29
  nameserver: # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
    - https://dns.adguard-dns.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://dns.cloudflare.com/dns-query#ecs=1.1.1.1/24&ecs-override=true
    - https://dns.google/dns-query#ecs=1.1.1.1/24&ecs-override=true
  nameserver-policy: # 指定域名查询的解析服务器，优先于 nameserver/fallback 查询
    "RULE-SET:China,Lan": 
      - https://dns.alidns.com/dns-query#ecs=223.5.5.5/24&ecs-override=true
      - https://doh.pub/dns-query#ecs=223.5.5.5/24&ecs-override=true
  proxy-server-nameserver:  # 代理节点域名解析服务器，仅用于解析代理节点的域名，如果不填则遵循 nameserver-policy、nameserver 和 fallback 的配置
    - https://dns.alidns.com/dns-query#ecs=223.5.5.5/24&ecs-override=true
    - https://doh.pub/dns-query#ecs=223.5.5.5/24&ecs-override=true
  proxy-server-nameserver-policy: # 格式同nameserver-policy，仅用于节点域名解析，优先于proxy-server-nameserver查询，自定义机场在此添加DNS
    '*.digital-nvme.com': 
      - 8.138.94.132:8053


# GEO配置
geodata-mode: false
geo-auto-update: true
geo-update-interval: 24
geodata-loader: memconservative
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  asn: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

# 入站
tun:
  enable: false
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack: [ any:53, tcp://any:53 ]

# 嗅探
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    TLS:
      ports: [ 443, 8443 ]
    HTTP:
      ports: [ 80, 8080-8880 ]
      override-destination: true
    QUIC:
      ports: [ 443, 8443 ]
  skip-domain:
     - "Mijia Cloud"
     - "+.push.apple.com"

# 实验性功能
experimental:
  quic-go-disable-gso: true
  sniff-tls-sni: true

# 面板设置
external-ui-name: zashboard
external-ui: ui
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
secret: Wans
external-controller: '0.0.0.0:9090'

# 代理节点: 可以将自己的节点放在这里
# proxies:
#   - name: "[SS] domain"
#     type: ss
#     server: abaosd.jasidofnbasdfij.com
#     port: 443
#     cipher: chacha20-ietf-poly1305
#     password: 4nggcF
#     udp: true

# 节点筛选锚点
FilterHK: &FilterHK "(?i)(?=.*(🇭🇰|香港|港|HK|HKG|hong ?kong))"
FilterTW: &FilterTW "(?i)(?=.*(🇹🇼|台湾|台|TW|TWN|taiwan|taipei))"
FilterSG: &FilterSG "(?i)(?=.*(🇸🇬|新加坡|狮城|新|SG|SGP|singapore))"
FilterJP: &FilterJP "(?i)(?=.*(🇯🇵|日本|日|JP|JPN|japan|tokyo|osaka))"
FilterKR: &FilterKR "(?i)(?=.*(🇰🇷|韩国|韩|KR|KOR|korea|seoul))"
FilterUS: &FilterUS "(?i)(?=.*(🇺🇸|美国|美|US|USA|united ?states|america|los angeles|san jose|silicon valley))"
FilterUK: &FilterUK "(?i)(?=.*(🇬🇧|英国|英|GBR|UK|united ?kingdom|london))"
FilterHM: &FilterHM "(?i)(?=.*(家宽|DMIT|AT))"


# 代理组
proxy-groups:
  - { name: 手动选择,     type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Rocket.png }
  - { name: 家宽选择,     type: select, include-all: true, filter: "(?i)(?=.*(家宽|DMIT))", icon: https://telegraph-image-92x.pages.dev/file/984a987871f136f5a0bfb-ba1c413cc3c3e06847.png }
  - { name: GLOBAL,      type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Global.png }

  # ===================== AI大模型 =====================
  - { name: OpenAI,     type: select, include-all: true, filter: *FilterHM, proxies: [家宽选择], icon: https://fastly.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/openai.png }
  - { name: Gemini,     type: select, include-all: true, filter: *FilterHM, proxies: [家宽选择], icon: https://fastly.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/gemini-color.png, url: "https://www.google.com/generate_204" }
  - { name: Claude,     type: select, include-all: true, filter: *FilterHM, proxies: [家宽选择], icon: https://fastly.jsdelivr.net/gh/lobehub/lobe-icons@master/packages/static-png/light/claude-color.png }

  # ===================== 媒体 & 娱乐 =====================
  - { name: Apple,       type: select, include-all: true, proxies: [DIRECT], icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Apple.png, url: "https://www.apple.com/library/test/success.html" }
  - { name: Disney,      type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Disney.png }
  - { name: Netflix,     type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Netflix.png }
  - { name: Spotify,     type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Spotify.png }
  - { name: TikTok,      type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/TikTok.png }
  - { name: YouTube,     type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/YouTube.png, url: "https://www.youtube.com/generate_204" }

  # ===================== 生产力 & 常用 =====================
  - { name: Emby,        type: select, include-all: true, proxies: [DIRECT], icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Emby.png }
  - { name: Github,      type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/GitHub.png }
  - { name: Google,      type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Google_Search.png, url: "https://www.google.com/generate_204" }
  - { name: Microsoft,   type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Microsoft.png, url: "http://www.msftconnecttest.com/connecttest.txt" }
  - { name: OneDrive,    type: select, include-all: true, proxies: [DIRECT], icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/OneDrive.png }

  # ===================== 社交 & 即时通讯 ===================== https://macosicons.com/#/
  - { name: Twitter(X),  type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Twitter(X).png }
  - { name: Facebook,    type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Facebook.png }
  - { name: Telegram,    type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Telegram.png }
  - { name: WhatsApp,    type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/WhatsApp.png }

  # ===================== 游戏 & 下载 =====================
  - { name: Steam,       type: select, include-all: true, icon: https://fastly.jsdelivr.net/gh/0xWans/Qure@master/IconSet/Color/Steam.png }



# 规则锚点
rule-anchor:
  # 规则集锚点
  BehaviorDN: &BehaviorDN {type: http, interval: 86400, format: mrs,  behavior: domain }
  BehaviorIP: &BehaviorIP {type: http, interval: 86400, format: mrs,  behavior: ipcidr }
  BehaviorCL: &BehaviorCL {type: http, interval: 86400, format: yaml, behavior: classical }

# 规则集配置
rule-providers:
  # 域名规则集
  category-ads-all: { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs }
  Apple:            { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple@cn.mrs }
  China:            { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs }
  Claude:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/anthropic.mrs }
  Disney:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/disney.mrs }
  Emby:             { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-emby.mrs }
  Gemini:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google-gemini.mrs }
  Github:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/github.mrs }
  Google:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs }
  Lan:              { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs }
  Microsoft:        { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs  }
  Netflix:          { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/netflix.mrs }
  OpenAI:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/openai.mrs }
  OneDrive:         { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/onedrive.mrs }
  Steam:            { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam.mrs }
  Spotify:          { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/spotify.mrs }
  TikTok:           { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/tiktok.mrs }
  WhatsApp:         { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/whatsapp.mrs }
  Twitter:          { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/x.mrs }
  Facebook:         { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/facebook.mrs }
  Telegram:         { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/telegram.mrs }
  YouTube:          { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/youtube.mrs }
  DNSLeak:          { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/0xWans/my-backup@main/clash/rules/DNSLeak.mrs }

  # IP规则集
  ChinaIP:          { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs }
  GoogleIP:         { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/google.mrs }
  LanIP:            { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs }
  NetflixIP:        { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/netflix.mrs }
  TwitterIP:        { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/twitter.mrs }
  TelegramIP:       { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/telegram.mrs }
  FacebookIP:       { <<: *BehaviorIP, url: https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/facebook.mrs }

  # 应用规则集
  ChinaAPP:       { <<: *BehaviorCL, url: https://fastly.jsdelivr.net/gh/0xWans/my-backup@main/clash/rules/Process/ChinaAPP.yaml }
  Direct:         { <<: *BehaviorDN, url: https://fastly.jsdelivr.net/gh/0xWans/my-backup@main/clash/rules/Direct.mrs }

# 官方配置文档: https://wiki.metacubex.one/config/rules/
rules:
  # 自定义规则集
  - RULE-SET,Direct,DIRECT
  - AND,((DST-PORT,443),(NETWORK,UDP),(NOT,((RULE-SET,ChinaIP))),(NOT,((RULE-SET,China)))),REJECT  # 阻止海外 QUIC 流量泄漏
  
  # 应用规则集
  - RULE-SET,ChinaAPP,DIRECT  

  # 域名规则集-按照优先级顺序排列
  - DOMAIN,dogtv.ovohi.de,DIRECT
  - DOMAIN-KEYWORD,jufyun,DIRECT
  - RULE-SET,category-ads-all,REJECT
  - RULE-SET,YouTube,YouTube
  - RULE-SET,Github,Github
  - RULE-SET,OpenAI,OpenAI
  - RULE-SET,Gemini,Gemini
  - RULE-SET,Google,Google
  - RULE-SET,Apple,Apple
  - RULE-SET,Claude,Claude
  - RULE-SET,Twitter,Twitter(X)
  - RULE-SET,Facebook,Facebook
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Spotify,Spotify
  - RULE-SET,TikTok,TikTok
  - RULE-SET,WhatsApp,WhatsApp
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Netflix,Netflix
  - RULE-SET,Disney,Disney
  - RULE-SET,Steam,Steam
  - RULE-SET,Emby,Emby
  - RULE-SET,Lan,DIRECT
  - RULE-SET,China,DIRECT

  # IP规则集-按照优先级顺序排列
  - RULE-SET,LanIP,DIRECT,no-resolve
  - RULE-SET,ChinaIP,DIRECT,no-resolve
  - RULE-SET,GoogleIP,Google,no-resolve
  - RULE-SET,TelegramIP,Telegram,no-resolve
  - RULE-SET,TwitterIP,Twitter(X),no-resolve
  - RULE-SET,FacebookIP,Facebook,no-resolve

  # 默认规则集
  - MATCH,手动选择
